### ISSUE TITLE
Couldn't add library to mbed studio 

### ISSUE THREAD

**Issue by Ardatufekci** [Alphatronics/mbed-os-example-canopen#1]
I am sorry in advance if this is an easy problem to fix but I couldn't do it.

While trying to import the library I got this error:

An error happened while processing the library https://github.com/Alphatronics/CANopenNode/. Commit a8e50277052bfb3194358eda21b663a065265d7d does not exist

**Comment by geoffrey-vl** [comment]
Hi @Ardatufekci ,
Well, you can always try to pull the library and checkout the commit directly, outside mbed studio, I haven't worked with that IDE so far. However, in this case I don't believe it's an issue with git, but basically something related to the some removal of a branch where I was testing with at the time.
Anyway, you may be able to try the fwupgrade branch, I've checked the canopen library and it should find it.
One other way to fix this is to edit the .lib file after you've pulled the sources, and re-deploy the libraries after the edit. You can for example change that library commit to the latest "stable" that I've been testing with in one of my private projects, being 581f0d70a15106ad6424b6b8488531185ecf56b8. It's based upon the stable canopennode 1.3.

We're not really maintaining this example project, it was something to get us started. But I'm open for feedback and PR's!

**Comment by geoffrey-vl** [comment]
Fixed in [v1.1](https://github.com/Alphatronics/mbed-os-example-canopen/tree/v1.1) branch
