### ISSUE TITLE
mbed import fail

### ISSUE THREAD

**Issue by tshh** [Alphatronics/mbed-os-example-canopen#2]
input: 
mbed import mbed-os-example-canopen
output: 
[mbed] Working path "/home/tshh" (directory)
[mbed] Importing program "mbed-os-example-canopen" from "https://github.com/ARMmbed/mbed-os-example-canopen" at latest revision in the current branch
Username for 'https://github.com': tshh
Password for 'https://tshh@github.com': 
[mbed] ERROR: Unable to clone repository (https://github.com/ARMmbed/mbed-os-example-canopen)
---

seems  this repo: https://github.com/ARMmbed/mbed-os-example-canopen  
doesn't exist anymore.

input: 
mbed import https://github.com/Alphatronics/mbed-os-example-canopen.git
output:
[mbed] Working path "/home/tshh" (directory)
[mbed] Importing program "mbed-os-example-canopen" from "https://github.com/Alphatronics/mbed-os-example-canopen.git" at latest revision in the current branch
[mbed] Adding library "CANopenNode" from "https://github.com/Alphatronics/CANopenNode" at rev #a8e50277052b
fatal: reference is not a tree：a8e50277052bfb3194358eda21b663a065265d7d                 
[mbed] ERROR: Unable to update "CANopenNode" to rev #a8e50277052b
---

**Comment by geoffrey-vl** [comment]
> seems this repo: https://github.com/ARMmbed/mbed-os-example-canopen
doesn't exist anymore.

Well, you've just opened a github issue on that repo, so my bet is that it does exist. However it seems you're having issue importing anything from github... try mbed import with ssh instead, or try to clone the repo directly using git and next execute `mbed deploy`.

> [mbed] ERROR: Unable to update "CANopenNode" to rev #a8e50277052b

See #1

**Comment by tshh** [comment]
(mbed) tshh@Ubuntu18-PD:~$ git clone https://github.com/Alphatronics/mbed-os-example-canopen.git
正克隆到 'mbed-os-example-canopen'...
remote: Enumerating objects: 502, done.
remote: Total 502 (delta 0), reused 0 (delta 0), pack-reused 502
接收对象中: 100% (502/502), 476.88 KiB | 450.00 KiB/s, 完成.
处理 delta 中: 100% (168/168), 完成.
(mbed) tshh@Ubuntu18-PD:~$ cd mbed-os-example-canopen/
(mbed) tshh@Ubuntu18-PD:~/mbed-os-example-canopen$ mbed deploy
[mbed] Working path "/home/tshh/mbed-os-example-canopen" (program)
[mbed] Adding library "CANopenNode" from "https://github.com/Alphatronics/CANopenNode" at rev #a8e50277052b
fatal: 引用不是一个树：a8e50277052bfb3194358eda21b663a065265d7d                 
[mbed] ERROR: Unable to update "CANopenNode" to rev #a8e50277052b

got the same result.
yes, i know network could be a problem, this time VPN is on.

**Comment by geoffrey-vl** [comment]
> See #1

Please follow these instructions first
